import type { RevisedStory } from './RevisionCase';
import owl from './revised/owl.json';
import forest from './revised/forest.json';
import cloud from './revised/cloud.json';
import museum from './revised/museum.json';
import greenhouse from './revised/greenhouse.json';
import theatre from './revised/theatre.json';
import aquarium from './revised/aquarium.json';
import bakery from './revised/bakery.json';
import lighthouse from './revised/lighthouse.json';
import library from './revised/library.json';
import park from './revised/park.json';
export { localeOf } from './RevisionCase';
export const revisedStories: RevisedStory[] = [owl,forest,cloud,museum,greenhouse,theatre,aquarium,bakery,lighthouse,library,park].map(story=>story as RevisedStory);
