import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, Fingerprint, Lightbulb, MapPin, NotebookPen, Search, Sparkles, Undo2 } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { translations, type Language } from './i18n';
import forestCopy from './forest.json';
import { validateResponse, type ResponseKind } from './revision-game';
export type RevisedStep = { title: string; situation: string; evidence: string[]; question: string; kind: ResponseKind; options: string[]; answer: string | number | number[]; explanation: string; outcome: string; next: string; hints: string[]; scene: number };
export type RevisedStory = { id: string; number: string; locales: Record<Language,{title:string;intro:string;ending:string;question:string;steps:RevisedStep[]}> };
const labels = {
  ru: { facts: 'Что известно', answer: 'Твой ответ', correct: 'Верно', outcome: 'Что удалось выяснить', empty: 'Здесь появятся выводы расследования.', order: 'Выбери карточки в нужном порядке.' },
  pl: { facts: 'Co wiemy', answer: 'Twoja odpowiedź', correct: 'Zgadza się', outcome: 'Czego się dowiedzieliśmy', empty: 'Tutaj pojawią się wnioski ze śledztwa.', order: 'Wybierz karty w odpowiedniej kolejności.' },
  en: { facts: 'What we know', answer: 'Your answer', correct: 'Correct', outcome: 'What we learned', empty: 'Your findings will appear here.', order: 'Select the cards in the right order.' },
  uk: { facts: 'Що відомо', answer: 'Твоя відповідь', correct: 'Правильно', outcome: 'Що вдалося з’ясувати', empty: 'Тут з’являться висновки розслідування.', order: 'Обери картки в потрібному порядку.' },
};
export default function RevisionCase({ story, language, step, setStep, exit }: { story: RevisedStory; language: Language; step: number; setStep: (value:number)=>void; exit:()=>void }) {
 const t=story.locales[language], shared=translations[language], buttons=forestCopy[language], ui=labels[language];
 const [solved,setSolved]=useState(false),[wrong,setWrong]=useState(false),[hint,setHint]=useState(0),[answer,setAnswer]=useState(''),[order,setOrder]=useState<number[]>([]);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{ heading.current?.focus({preventScroll:true}); },[step]);
 const done=step===t.steps.length, task=t.steps[step];
 const advance=()=>{setSolved(false);setWrong(false);setHint(0);setAnswer('');setOrder([]);setStep(step+1);};
 function check(value:string|number[]) { if(solved)return; const ok=validateResponse(task.kind,task.answer,value);setSolved(ok);setWrong(!ok); }
 if(step<0)return <div className="start forest-start"><section className="cover forest-cover"><div className="cover-shade"/><div className="cover-label"><Fingerprint size={19}/>{shared.secret}</div><div className="cover-title"><span className="eyebrow">{shared.case} {story.number}</span><h1 ref={heading} tabIndex={-1}>{t.title}</h1><p>{buttons[30]}</p></div><div className="case-stamp">{shared.unsolved}</div></section><section className="brief"><span className="eyebrow">{shared.case} {story.number}</span><h2>{shared.greeting}</h2><p>{t.intro}</p><div className="mission"><Search/><div><strong>{shared.motto}</strong><p>{buttons[30]}</p></div></div><button className="primary" onClick={()=>setStep(0)}>{shared.start}<ArrowRight size={20}/></button><p className="quiet">{shared.calm}</p><button className="text-button" onClick={exit}>{buttons[8]}</button></section></div>;
 return <div className="forest-case"><div className="game-top"><span className="eyebrow">{done?shared.closed:t.title}</span><span>{Math.min(step+1,t.steps.length)} / {t.steps.length}</span></div><Progress value={done?100:step/t.steps.length*100} aria-label={shared.progress}/><div className="scene-window forest-window" aria-hidden="true"/><div className="game-grid"><section className="puzzle"><div className="location"><span>{done?<Sparkles/>:<MapPin/>}</span>{shared.case} {story.number}</div><h1 ref={heading} tabIndex={-1}>{done?shared.end.solved:task.title}</h1>
 {done?<><div className="finish-badge"><Check size={38}/><span>{shared.case} {story.number}<br/><strong>{shared.end.solved}</strong></span></div><p>{t.ending}</p><blockquote>{t.question}</blockquote></>:<>
 <p>{task.situation}</p>{task.evidence.length>0&&<div className="paper"><span className="paper-label">{ui.facts}</span><ul>{task.evidence.map((fact,i)=><li key={i}>{fact}</li>)}</ul></div>}{task.question&&<h2 className="task-question">{task.question}</h2>}
 {task.kind==='choice'?<div className="story-options">{task.options.map((option,i)=><button className="answer" key={i} disabled={solved} onClick={()=>check(String(i))}>{option}</button>)}</div>:task.kind==='order'?<><p className="quiet">{ui.order}</p><ol className="selected-order" aria-live="polite">{order.map(id=><li key={id}>{task.options[id]}</li>)}</ol><div className="story-options">{task.options.map((option,i)=><button className="answer" key={i} disabled={solved||order.includes(i)} onClick={()=>{setOrder([...order,i]);setWrong(false);}}>{option}</button>)}</div>{!solved&&<><button className="text-button" disabled={!order.length} onClick={()=>{setOrder(order.slice(0,-1));setWrong(false);}}><Undo2 size={18}/>{shared.note.undo}</button><button className="primary" disabled={order.length!==task.options.length} onClick={()=>check(order)}>{buttons[4]}</button></>}</>:<form onSubmit={event=>{event.preventDefault();check(answer);}}><label htmlFor="revision-answer">{ui.answer}</label><input id="revision-answer" className="time-input" value={answer} disabled={solved} inputMode={task.kind==='time'?'numeric':'decimal'} placeholder={task.kind==='time'?'00:00':undefined} autoComplete="off" enterKeyHint="done" onChange={event=>{let value=event.target.value;if(task.kind==='time'){const digits=value.replace(/\D/g,'').slice(0,4);value=digits.length>2?`${digits.slice(0,2)}:${digits.slice(2)}`:digits;}setAnswer(value.slice(0,12));setWrong(false);}}/>{!solved&&<button className="primary" type="submit">{buttons[4]}<ArrowRight size={18}/></button>}</form>}
 <div aria-live="polite">{wrong&&<p className="feedback">{buttons[7]}</p>}{solved&&<div className="success"><strong><Check size={19}/>{ui.correct}</strong><p>{task.explanation}</p>{task.outcome!==task.explanation&&<><strong>{ui.outcome}</strong><p>{task.outcome}</p></>}<button className="primary" onClick={advance}>{task.next}<ArrowRight size={18}/></button></div>}</div>
 {!solved&&<div className="hint-box"><button className="text-button" disabled={hint===task.hints.length} onClick={()=>setHint(hint+1)}><Lightbulb size={19}/>{hint?shared.moreHint:shared.hint}<span>{hint}/{task.hints.length}</span></button>{hint>0&&<p aria-live="polite">{task.hints[hint-1]}</p>}</div>}
 </>}<button className="text-button" onClick={exit}>{buttons[8]}</button></section><aside className="notebook"><span className="eyebrow"><NotebookPen size={16}/>{buttons[29]}</span><h2>{shared.notebookTitle}</h2>{step===0&&!solved&&<p>{ui.empty}</p>}{t.steps.slice(0,done?t.steps.length:step+(solved?1:0)).map((item,i)=><div className="clue" key={i}><span>0{i+1} · {item.title}</span><p>{item.outcome}</p></div>)}<div className="partner"><Lightbulb size={20}/><p>{shared.partner}</p></div></aside></div></div>;
}
