from common import step, write_case, add, T, hm
def variants():
    out = []
    for lag, c1, c2, lf, need in [(4, '14:50', '15:02', 7, 40), (3, '14:47', '15:01', 6, 45), (3, '14:44', '14:58', 8, 36), (2, '14:53', '15:03', 5, 42)]:
        w1, w2 = add(c1, lag), add(c2, lag)
        wlen = T(w2) - T(w1)
        k = [add(w1, -4), add(w1, 3), add(w1, 9), add(w1, 16)]
        # Kim: gaps 7, 6, 7 minutes are all shorter than the 8-minute round trip.
        assert all(T(k[i + 1]) - T(k[i]) < 8 for i in range(3)) and T(k[0]) < T(w1) < T(w2) < T(k[3])
        g, ca, cb = add(w1, 2), add(w1, 7), add(w1, 12)
        assert T(cb) >= T(w2) - 5  # After the last canteen photo Lev cannot reach the case inside the window.
        t0 = add(w1, 8); sofar = T('15:28') - T(t0); rem = need - sofar
        assert 0 < rem < 26
        done = add('15:34', rem); back = add(done, 4); spare = T('16:00') - T(back)
        assert spare > 0
        v = dict(lag=lag, c1=c1, c2=c2, w1=w1, w2=w2, wlen=wlen, nc1=add(c1, -lag), nc2=add(c2, -lag),
                 k1=k[0], k2=k[1], k3=k[2], k4=k[3], lf=lf, g=g, ca=ca, cb=cb, gcam=add(g, lf), cacam=add(ca, lf), cbcam=add(cb, lf),
                 sp=add(w1, 4), lp=add(w1, 11), t0=t0, need=need, sofar=sofar, rem=rem, done=done, back=back, spare=spare)
        out.append({'values': v, 'answers': [2, [0, 1, 3], 1, back]})
    return out
L = {}
L['ru'] = {
 "title": "Тайна золотой совы",
 "intro": "Из витрины в коридоре второго этажа пропала картонная золотая сова. На подставке лужица, рядом размокшая записка, в которой читаются только обрывки: «...сушу... верну к ...». В 14:30 учительница сфотографировала витрину с совой, в 15:12 витрина уже пуста. После обеда в этом крыле были четверо: Мира украшала двор, Лев снимал школу для стенгазеты, Саша готовил театр к репетиции, Ким дежурил в библиотеке. Никто не признаётся. Выставка открывается в 16:00. Нужно понять, кто забрал сову, зачем, и успеет ли она вернуться.",
 "ending": "Сову никто не крал. Саша задел вазу, испугался, что картон размокнет, отнёс сову сушиться в театр и оставил записку, которая тут же размокла. Запись камеры дала окно в {wlen|минуту|минуты|минут}. Турникет, журнал библиотеки и снимки Льва исключили троих. Журнал бумаги и капли воды связали Сашу с театром. Сова вернулась на витрину в {back}, за {spare|минуту|минуты|минут} до открытия. Учительница попросила Сашу в следующий раз сразу говорить взрослым.",
 "question": "У Саши не было алиби, а капли воды вели в театр. Почему вторая улика сильнее первой?",
 "steps": [
  step("Когда унесли сову?", "Дежурная нашла запись камеры коридора, но камера писала с перебоями: часть времени пропала. На всех сохранившихся кадрах видна витрина. Дежурная сверила часы камеры с точными и записала поправку.",
   ["С 14:30 до {c1} по часам камеры запись сохранилась: сова на месте всё это время.", "С {c1} до {c2} по часам камеры записи нет.", "С {c2} до 15:12 по часам камеры запись сохранилась: витрина пуста всё это время.", "Часы камеры отстают от точного времени на {lag|минуту|минуты|минут}."],
   "В каком промежутке точного времени сову могли унести?", "choice", ["С {c1} до {c2}", "С {nc1} до {nc2}", "С {w1} до {w2}", "С 14:30 до 15:12"],
   ["Это промежуток по часам камеры. Они отстают, значит настоящее время другое.", "Отстающие часы показывают меньше, чем на самом деле. Поправку нужно прибавить, а не вычесть.", "", "Между снимками учительницы 42 минуты, но запись камеры позволяет сузить промежуток."],
   "Последний кадр с совой: {c1} по камере, а по точному времени на {lag|минуту|минуты|минут} больше, {w1}. Первый кадр без совы: {c2} по камере, то есть {w2}. Сову унесли между {w1} и {w2}.",
   "Окно всего {wlen|минута|минуты|минут}: с {w1} до {w2} по точному времени. Теперь проверим, кто из четверых мог в это время оказаться у витрины.", "Проверить, где были все четверо",
   ["Найди на записи два момента: последний кадр, где сова ещё есть, и первый кадр, где её уже нет.", "Отстающие часы показывают меньше, чем точные. Реши, прибавлять поправку или вычитать.", "Поправь оба конца промежутка на одно и то же число минут."], 0),
  step("У кого есть алиби?", "Дежурная собрала всё, что известно о четверых. Витрина стоит в коридоре второго этажа. Сову унесли между {w1} и {w2}. Проверь каждого: мог ли он опинуться у витрины хотя бы на минуту в этом промежутке. Все времена ниже точные, если не сказано иное.".replace('опинуться', 'оказаться'),
   ["Вход в школу один, через турникет, он записывает каждый проход. Мира вышла в 14:35 и вернулась в 15:20.", "Ким дежурил в библиотеке в другом крыле. От библиотеки до витрины идти 4 минуты. По журналу Ким выдавал книги в {k1}, {k2}, {k3} и {k4}.", "Лев всё время носил фотоаппарат, часы которого спешат на {lf|минуту|минуты|минут}. Снимки по часам фотоаппарата: спортзал в {gcam}, столовая в {cacam} и в {cbcam}.", "От спортзала до витрины идти 6 минут, от столовой до витрины 5 минут.", "Саша готовил театр. Репетиция закончилась в 14:50, театр в 2 минутах от витрины. После 14:50 Сашу никто не видел до 15:15."],
   "Отметь всех, кто не мог быть у витрины между {w1} и {w2}.", "multi", ["Мира", "Лев", "Саша", "Ким"], [],
   "Мира была за турникетом с 14:35 до 15:20. Ким отмечен в библиотеке в {k2} и {k3}: между ними 6 минут, а дорога до витрины и обратно занимает 8. Снимки Льва по точному времени: спортзал {g}, столовая {ca} и {cb}. Между снимками по 5 минут, а от спортзала до витрины 6 минут, от столовой 5, и ещё нужно успеть назад. Ни у кого из троих нет свободного зазора. Только Саша после 14:50 никем не отмечен, а театр в двух минутах от витрины.",
   "Мира, Ким и Лев не могли быть у витрины. Остаётся Саша. Но отсутствие алиби ещё не доказательство: нужны улики, которые связывают именно его с совой.", "Искать улики",
   ["Проверяй каждого по отдельности: где он точно был в промежутке и сколько минут ему идти до витрины.", "У Льва часы фотоаппарата спешат. Сначала переведи все его снимки в точное время.", "У Кима и Льва есть отметки времени. Посчитай минуты между соседними отметками и сравни с дорогой до витрины и обратно."], 1),
  step("Какая улика настоящая?", "Библиотекарь показывает журнал выдачи бумаги, а дежурная прошла по коридору с фонариком. Одна запись в журнале выглядит подозрительно, но не спеши: сначала реши, что из найденного действительно связано с совой.",
   ["Журнал: {sp} Саша взял 3 листа плотной бумаги. {lp} Лев взял 1 лист цветной бумаги для стенгазеты.", "На полу капли воды. Они ведут от витрины к лестнице и обрываются у двери театра.", "На подставке совы след от опрокинутой вазы, сама ваза стоит рядом пустая.", "В записке читаются обрывки: «...сушу... верну к ...». Почерк размыт."],
   "Какой вывод верен?", "choice", ["Бумагу брали и Саша, и Лев, поэтому подозреваемых снова двое", "Саша взял плотную бумагу в {sp}, внутри окна, а капли ведут в театр, где он работал. Обе улики указывают на него", "Лев взял бумагу позже, в {lp}, значит это он унёс сову", "Записка размыта и ничего не доказывает, поэтому улик пока нет"],
   ["Лев не мог быть у витрины, это уже доказано снимками. Запись о нём в журнале ничего не меняет.", "", "У Льва есть алиби на всё окно. Одна строка в журнале его не отменяет.", "Записка сама по себе слабая улика. Но есть ещё журнал и капли: сложи их вместе."],
   "Запись Льва настоящая, но Лев исключён снимками, поэтому это ложный след. Запись Саши попадает в окно {w1}-{w2}, а плотная бумага нужна, чтобы сушить мокрую поделку. Капли ведут именно в театр, где Саша работал. Записка подтверждает: сову не украли, а унесли сушить.",
   "Версия: Саша задел вазу, вода залила подставку, он взял в библиотеке плотную бумагу и унёс сову сушиться в театр, а записку оставил у витрины. Проверим версию в театре и решим, успеет ли сова вернуться к 16:00.", "Идти в театр",
   ["Сначала вспомни, кто уже исключён. Улика против исключённого человека ничего не меняет.", "Проверь время каждой записи журнала: попадает ли оно в окно {w1}-{w2}?", "Куда ведут капли и кто там работал в это время?"], 2),
  step("Успеет ли сова на выставку?", "В театре Саша сушит сову на плотной бумаге под лампой. Он подтверждает: задел вазу, испугался, что картон размокнет, и отнёс сову сушиться, а записку оставил у витрины. Теперь главное: выполнить инструкцию, не сорвать репетицию и вернуть сову к открытию.",
   ["Саша положил сову под лампу в {t0}.", "Инструкция к набору: после намокания держать под лампой не меньше {need|минуты|минут|минут}, потом проверить, что картон сухой. Переносить можно и раньше, но время под лампой всё равно должно набраться.", "Репетиция в театре начинается в 15:30. Саша унесёт сову со сцены в 15:28.", "В библиотеке есть такая же лампа. От театра до библиотеки идти 6 минут, от библиотеки до витрины 4 минуты.", "Выставка открывается в 16:00."],
   "Во сколько самое раннее сова вернётся на витрину, если выполнить инструкцию? Введи время ЧЧ:ММ.", "time", [], [],
   "В театре под лампой с {t0} до 15:28: {sofar|минута|минуты|минут}. До {need} не хватает {rem}. Дорога до библиотеки 6 минут, под лампу сова попадает в 15:34, ещё {rem|минута|минуты|минут} дают {done}. Проверка сухости и 4 минуты до витрины: сова на месте в {back}, за {spare|минуту|минуты|минут} до открытия.",
   "План готов: в 15:28 со сцены, в 15:34 под лампу в библиотеке, в {done} проверка, в {back} сова на витрине. Выставка откроется вовремя.", "Вернуть сову на выставку",
   ["Разбей задачу на части: сколько минут сова уже под лампой, сколько ещё нужно, дорога до библиотеки, дорога до витрины.", "Минуты в дороге между лампами не считаются: сова в это время не под лампой.", "После библиотеки сову ещё нужно донести до витрины."], 3)
 ]}
L['pl'] = {
 "title": "Tajemnica złotej sowy",
 "intro": "Z gabloty na korytarzu drugiego piętra zniknęła złota sowa z kartonu. Na podstawce kałuża, obok rozmokła karteczka, z której da się odczytać tylko strzępy: „...suszę... oddam o...”. O 14:30 nauczycielka sfotografowała gablotę z sową, o 15:12 gablota była już pusta. Po obiedzie w tym skrzydle były cztery osoby: Mira dekorowała podwórko, Lew fotografował szkołę do gazetki, Sasza szykował teatr do próby, Kim miał dyżur w bibliotece. Nikt się nie przyznaje. Wystawa zaczyna się o 16:00. Trzeba ustalić, kto zabrał sowę, po co, i czy zdąży wrócić.",
 "ending": "Nikt nie ukradł sowy. Sasza potrącił wazon, przestraszył się, że karton rozmoknie, zaniósł sowę do teatru, żeby wyschła, i zostawił karteczkę, która od razu zamokła. Nagranie z kamery dało okno {wlen|minuty|minut|minut}. Bramka, dziennik biblioteki i zdjęcia Lwa wykluczyły trzy osoby. Dziennik papieru i krople wody połączyły Saszę z teatrem. Sowa wróciła do gabloty o {back}, {spare|minutę|minuty|minut} przed otwarciem. Nauczycielka poprosiła Saszę, żeby następnym razem od razu powiedział dorosłym.",
 "question": "Sasza nie miał alibi, a krople wody prowadziły do teatru. Dlaczego druga poszlaka jest mocniejsza niż pierwsza?",
 "steps": [
  step("Kiedy zabrano sowę?", "Woźna znalazła nagranie z kamery na korytarzu, ale kamera nagrywała z przerwami: część czasu przepadła. Na wszystkich zachowanych klatkach widać gablotę. Woźna porównała zegar kamery z dokładnym czasem i zapisała różnicę.",
   ["Od 14:30 do {c1} według zegara kamery nagranie się zachowało: sowa jest na miejscu przez cały ten czas.", "Od {c1} do {c2} według zegara kamery nagrania nie ma.", "Od {c2} do 15:12 według zegara kamery nagranie się zachowało: gablota jest pusta przez cały ten czas.", "Zegar kamery spóźnia się o {lag|minutę|minuty|minut} względem dokładnego czasu."],
   "W jakim przedziale dokładnego czasu mogła zniknąć sowa?", "choice", ["Od {c1} do {c2}", "Od {nc1} do {nc2}", "Od {w1} do {w2}", "Od 14:30 do 15:12"],
   ["To przedział według zegara kamery. Zegar się spóźnia, więc prawdziwy czas jest inny.", "Spóźniający się zegar pokazuje mniej niż jest naprawdę. Różnicę trzeba dodać, a nie odjąć.", "", "Między zdjęciami nauczycielki mijają 42 minuty, ale nagranie z kamery pozwala zawęzić przedział."],
   "Ostatnia klatka z sową: {c1} według kamery, czyli o {lag|minutę|minuty|minut} więcej według dokładnego czasu, {w1}. Pierwsza klatka bez sowy: {c2} według kamery, czyli {w2}. Sowę zabrano między {w1} a {w2}.",
   "Okno to tylko {wlen|minuta|minuty|minut}: od {w1} do {w2} dokładnego czasu. Teraz sprawdźmy, kto z czworga mógł być wtedy przy gablocie.", "Sprawdź, gdzie byli wszyscy",
   ["Znajdź na nagraniu dwa momenty: ostatnią klatkę, na której sowa jeszcze jest, i pierwszą, na której już jej nie ma.", "Spóźniający się zegar pokazuje mniej niż dokładny. Zdecyduj, czy różnicę dodać, czy odjąć.", "Popraw oba końce przedziału o tę samą liczbę minut."], 0),
  step("Kto ma alibi?", "Woźna zebrała wszystko, co wiadomo o czworgu. Gablota stoi na korytarzu drugiego piętra. Sowę zabrano między {w1} a {w2}. Sprawdź każdego: czy mógł znaleźć się przy gablocie choćby na minutę w tym przedziale. Wszystkie godziny poniżej są dokładne, chyba że napisano inaczej.",
   ["Do szkoły jest jedno wejście, przez bramkę, która zapisuje każde przejście. Mira wyszła o 14:35 i wróciła o 15:20.", "Kim miał dyżur w bibliotece w drugim skrzydle. Z biblioteki do gabloty idzie się 4 minuty. Według dziennika Kim wydawał książki o {k1}, {k2}, {k3} i {k4}.", "Lew cały czas miał przy sobie aparat, którego zegar spieszy się o {lf|minutę|minuty|minut}. Zdjęcia według zegara aparatu: sala gimnastyczna o {gcam}, stołówka o {cacam} i o {cbcam}.", "Z sali gimnastycznej do gabloty idzie się 6 minut, ze stołówki do gabloty 5 minut.", "Sasza szykował teatr. Próba skończyła się o 14:50, teatr jest 2 minuty od gabloty. Po 14:50 nikt nie widział Saszy aż do 15:15."],
   "Zaznacz wszystkich, którzy nie mogli być przy gablocie między {w1} a {w2}.", "multi", ["Mira", "Lew", "Sasza", "Kim"], [],
   "Mira była za bramką od 14:35 do 15:20. Kim jest zapisany w bibliotece o {k2} i {k3}: między nimi 6 minut, a droga do gabloty i z powrotem zajmuje 8. Zdjęcia Lwa według dokładnego czasu: sala gimnastyczna {g}, stołówka {ca} i {cb}. Między zdjęciami po 5 minut, a z sali do gabloty idzie się 6 minut, ze stołówki 5, i jeszcze trzeba zdążyć wrócić. Nikt z tej trójki nie ma wolnej luki. Tylko Sasza po 14:50 nie jest nigdzie zapisany, a teatr jest dwie minuty od gabloty.",
   "Mira, Kim i Lew nie mogli być przy gablocie. Zostaje Sasza. Ale brak alibi to jeszcze nie dowód: potrzebne są poszlaki, które łączą właśnie jego z sową.", "Szukaj poszlak",
   ["Sprawdzaj każdego osobno: gdzie na pewno był w tym przedziale i ile minut idzie się stamtąd do gabloty.", "Zegar aparatu Lwa się spieszy. Najpierw przelicz wszystkie jego zdjęcia na dokładny czas.", "Kim i Lew mają zapisane godziny. Policz minuty między sąsiednimi zapisami i porównaj z drogą do gabloty i z powrotem."], 1),
  step("Która poszlaka jest prawdziwa?", "Bibliotekarka pokazuje dziennik wydawania papieru, a woźna przeszła korytarzem z latarką. Jeden zapis w dzienniku wygląda podejrzanie, ale nie spiesz się: najpierw zdecyduj, co z tego naprawdę ma związek z sową.",
   ["Dziennik: {sp} Sasza wziął 3 arkusze grubego papieru. {lp} Lew wziął 1 arkusz kolorowego papieru do gazetki.", "Na podłodze są krople wody. Prowadzą od gabloty do schodów i urywają się przy drzwiach teatru.", "Na podstawce sowy jest ślad po przewróconym wazonie, sam wazon stoi obok, pusty.", "Na karteczce da się odczytać strzępy: „...suszę... oddam o...”. Pismo jest rozmyte."],
   "Który wniosek jest poprawny?", "choice", ["Papier brali i Sasza, i Lew, więc znów mamy dwóch podejrzanych", "Sasza wziął gruby papier o {sp}, w oknie czasowym, a krople prowadzą do teatru, gdzie pracował. Obie poszlaki wskazują na niego", "Lew wziął papier później, o {lp}, więc to on zabrał sowę", "Karteczka jest rozmyta i niczego nie dowodzi, więc na razie nie ma poszlak"],
   ["Lew nie mógł być przy gablocie, to już udowodniły zdjęcia. Zapis o nim w dzienniku niczego nie zmienia.", "", "Lew ma alibi na całe okno. Jedna linijka w dzienniku tego nie odwołuje.", "Sama karteczka to słaba poszlaka. Ale jest jeszcze dziennik i krople: złóż je razem."],
   "Zapis o Lwie jest prawdziwy, ale Lew jest wykluczony przez zdjęcia, więc to fałszywy trop. Zapis o Saszy mieści się w oknie {w1}-{w2}, a gruby papier jest potrzebny do suszenia mokrej pracy. Krople prowadzą właśnie do teatru, gdzie pracował Sasza. Karteczka potwierdza: sowy nie ukradziono, tylko zabrano ją do wysuszenia.",
   "Wersja: Sasza potrącił wazon, woda zalała podstawkę, wziął z biblioteki gruby papier i zaniósł sowę do teatru, żeby wyschła, a karteczkę zostawił przy gablocie. Sprawdźmy tę wersję w teatrze i ustalmy, czy sowa zdąży wrócić na 16:00.", "Idź do teatru",
   ["Najpierw przypomnij sobie, kto jest już wykluczony. Poszlaka przeciwko wykluczonej osobie niczego nie zmienia.", "Sprawdź godzinę każdego zapisu w dzienniku: czy mieści się w oknie {w1}-{w2}?", "Dokąd prowadzą krople i kto tam wtedy pracował?"], 2),
  step("Czy sowa zdąży na wystawę?", "W teatrze Sasza suszy sowę na grubym papierze pod lampą. Potwierdza: potrącił wazon, przestraszył się, że karton rozmoknie, zaniósł sowę do suszenia, a karteczkę zostawił przy gablocie. Teraz najważniejsze: wykonać instrukcję, nie zepsuć próby i zwrócić sowę przed otwarciem.",
   ["Sasza położył sowę pod lampą o {t0}.", "Instrukcja zestawu: po zamoczeniu trzymać pod lampą co najmniej {need|minutę|minuty|minut}, potem sprawdzić, czy karton jest suchy. Można przenosić wcześniej, ale czas pod lampą i tak musi się uzbierać.", "Próba w teatrze zaczyna się o 15:30. Sasza zabierze sowę ze sceny o 15:28.", "W bibliotece jest taka sama lampa. Z teatru do biblioteki idzie się 6 minut, z biblioteki do gabloty 4 minuty.", "Wystawa zaczyna się o 16:00."],
   "O której najwcześniej sowa wróci do gabloty, jeśli wykonamy instrukcję? Wpisz czas GG:MM.", "time", [], [],
   "W teatrze pod lampą od {t0} do 15:28: {sofar|minuta|minuty|minut}. Do {need} brakuje {rem}. Droga do biblioteki 6 minut, pod lampę sowa trafia o 15:34, kolejne {rem|minuta|minuty|minut} daje {done}. Sprawdzenie, czy jest sucha, i 4 minuty do gabloty: sowa na miejscu o {back}, {spare|minutę|minuty|minut} przed otwarciem.",
   "Plan gotowy: o 15:28 ze sceny, o 15:34 pod lampę w bibliotece, o {done} sprawdzenie, o {back} sowa w gablocie. Wystawa zacznie się na czas.", "Odnieś sowę na wystawę",
   ["Podziel zadanie na części: ile minut sowa już jest pod lampą, ile jeszcze potrzeba, droga do biblioteki, droga do gabloty.", "Minut w drodze między lampami nie liczymy: sowa nie jest wtedy pod lampą.", "Po bibliotece sowę trzeba jeszcze donieść do gabloty."], 3)
 ]}
L['en'] = {
 "title": "The Golden Owl Mystery",
 "intro": "The cardboard golden owl has vanished from the display case in the second-floor corridor. There is a puddle on its stand and a soggy note beside it, of which only scraps can be read: “...drying... back by...”. At 14:30 the teacher photographed the case with the owl in it; at 15:12 the case was already empty. Four people were in this wing after lunch: Mira was decorating the courtyard, Lev was photographing the school for the newsletter, Sasha was preparing the theatre for a rehearsal, and Kim was on duty in the library. Nobody admits anything. The exhibition opens at 16:00. You need to work out who took the owl, why, and whether it can be back in time.",
 "ending": "Nobody stole the owl. Sasha knocked over the vase, worried the cardboard would go soggy, carried the owl to the theatre to dry and left a note that got wet straight away. The camera footage gave a {wlen}-minute window. The turnstile, the library log and Lev’s photos ruled out three people. The paper log and the water drops linked Sasha to the theatre. The owl was back in its case at {back}, {spare|minute|minutes} before opening. The teacher asked Sasha to tell an adult straight away next time.",
 "question": "Sasha had no alibi, and the water drops led to the theatre. Why is the second clue stronger than the first?",
 "steps": [
  step("When was the owl taken?", "The caretaker found the corridor camera footage, but the camera recorded with gaps: some of the time is missing. The display case is visible in every surviving frame. The caretaker compared the camera clock with the exact time and wrote down the difference.",
   ["From 14:30 to {c1} by the camera clock the footage survived: the owl is in place the whole time.", "From {c1} to {c2} by the camera clock there is no footage.", "From {c2} to 15:12 by the camera clock the footage survived: the case is empty the whole time.", "The camera clock is {lag|minute|minutes} slow compared with the exact time."],
   "In which interval of exact time could the owl have been taken?", "choice", ["From {c1} to {c2}", "From {nc1} to {nc2}", "From {w1} to {w2}", "From 14:30 to 15:12"],
   ["That is the interval by the camera clock. The clock is slow, so the real time is different.", "A slow clock shows less than the real time. You need to add the difference, not subtract it.", "", "There are 42 minutes between the teacher’s photos, but the camera footage lets you narrow the interval down."],
   "The last frame with the owl: {c1} by the camera, which is {lag|minute|minutes} more in exact time, {w1}. The first frame without the owl: {c2} by the camera, so {w2}. The owl was taken between {w1} and {w2}.",
   "The window is only {wlen|minute|minutes}: from {w1} to {w2} exact time. Now let’s check which of the four could have been at the case then.", "Check where everyone was",
   ["Find two moments in the footage: the last frame where the owl is still there and the first frame where it is gone.", "A slow clock shows less than the exact time. Decide whether to add the difference or subtract it.", "Correct both ends of the interval by the same number of minutes."], 0),
  step("Who has an alibi?", "The caretaker has gathered everything known about the four. The display case stands in the second-floor corridor. The owl was taken between {w1} and {w2}. Check each person: could they have been at the case for even a minute in that interval? All times below are exact unless stated otherwise.",
   ["The school has one entrance, through a turnstile that records every pass. Mira went out at 14:35 and came back at 15:20.", "Kim was on duty in the library in the other wing. It takes 4 minutes to walk from the library to the case. According to the log, Kim issued books at {k1}, {k2}, {k3} and {k4}.", "Lev carried his camera the whole time, and its clock is {lf|minute|minutes} fast. Photos by the camera clock: the gym at {gcam}, the canteen at {cacam} and at {cbcam}.", "It takes 6 minutes to walk from the gym to the case and 5 minutes from the canteen to the case.", "Sasha was preparing the theatre. The rehearsal ended at 14:50, and the theatre is 2 minutes from the case. Nobody saw Sasha after 14:50 until 15:15."],
   "Select everyone who could not have been at the case between {w1} and {w2}.", "multi", ["Mira", "Lev", "Sasha", "Kim"], [],
   "Mira was beyond the turnstile from 14:35 to 15:20. Kim is logged in the library at {k2} and {k3}: 6 minutes between them, while the walk to the case and back takes 8. Lev’s photos in exact time: the gym at {g}, the canteen at {ca} and {cb}. There are 5 minutes between photos, but it is 6 minutes from the gym to the case and 5 from the canteen, and he would still need to get back. None of the three has a free gap. Only Sasha is unaccounted for after 14:50, and the theatre is two minutes from the case.",
   "Mira, Kim and Lev could not have been at the case. That leaves Sasha. But having no alibi is not proof: we need clues that link him specifically to the owl.", "Look for clues",
   ["Check each person separately: where they definitely were during the interval and how many minutes it takes to walk from there to the case.", "Lev’s camera clock is fast. First convert all his photos to exact time.", "Kim and Lev have logged times. Count the minutes between neighbouring entries and compare with the walk to the case and back."], 1),
  step("Which clue is real?", "The librarian shows the paper log, and the caretaker has walked the corridor with a torch. One entry in the log looks suspicious, but do not rush: first decide what among the findings is really connected to the owl.",
   ["Log: {sp} Sasha took 3 sheets of thick paper. {lp} Lev took 1 sheet of coloured paper for the newsletter.", "There are drops of water on the floor. They lead from the case to the stairs and stop at the theatre door.", "On the owl’s stand there is a mark from the tipped-over vase; the vase itself stands beside it, empty.", "Scraps of the note can be read: “...drying... back by...”. The handwriting is smudged."],
   "Which conclusion is correct?", "choice", ["Both Sasha and Lev took paper, so there are two suspects again", "Sasha took thick paper at {sp}, inside the window, and the drops lead to the theatre, where he was working. Both clues point to him", "Lev took paper later, at {lp}, so he is the one who took the owl", "The note is smudged and proves nothing, so there are no clues yet"],
   ["Lev could not have been at the case; the photos already proved that. The log entry about him changes nothing.", "", "Lev has an alibi for the whole window. One line in a log does not cancel it.", "The note alone is a weak clue. But there is also the log and the drops: put them together."],
   "The entry about Lev is real, but Lev is ruled out by the photos, so it is a false trail. Sasha’s entry falls inside the {w1}-{w2} window, and thick paper is what you need to dry a wet craft. The drops lead precisely to the theatre, where Sasha was working. The note confirms it: the owl was not stolen, it was taken away to dry.",
   "The theory: Sasha knocked over the vase, water flooded the stand, he took thick paper from the library and carried the owl to the theatre to dry, leaving a note by the case. Let’s check this theory in the theatre and decide whether the owl can be back by 16:00.", "Go to the theatre",
   ["First remember who is already ruled out. A clue against a ruled-out person changes nothing.", "Check the time of each log entry: does it fall inside the {w1}-{w2} window?", "Where do the drops lead, and who was working there at the time?"], 2),
  step("Will the owl make the exhibition?", "In the theatre, Sasha is drying the owl on thick paper under a lamp. He confirms it: he knocked over the vase, worried the cardboard would go soggy, took the owl away to dry and left a note by the case. Now the main thing is to follow the instructions, not disrupt the rehearsal and return the owl before opening.",
   ["Sasha put the owl under the lamp at {t0}.", "The kit’s instructions: after getting wet, keep under a lamp for at least {need|minute|minutes}, then check that the cardboard is dry. It can be moved earlier, but the time under a lamp must still add up.", "The rehearsal in the theatre starts at 15:30. Sasha will take the owl off the stage at 15:28.", "The library has the same kind of lamp. It takes 6 minutes to walk from the theatre to the library and 4 minutes from the library to the case.", "The exhibition opens at 16:00."],
   "What is the earliest time the owl can be back in its case if the instructions are followed? Enter the time as HH:MM.", "time", [], [],
   "Under the lamp in the theatre from {t0} to 15:28: {sofar|minute|minutes}. {rem} more are needed to reach {need}. The walk to the library takes 6 minutes, so the owl is under the lamp again at 15:34, and {rem} more minutes give {done}. A dryness check and 4 minutes to the case: the owl is in place at {back}, {spare|minute|minutes} before opening.",
   "The plan is ready: off the stage at 15:28, under the library lamp at 15:34, checked at {done}, back in the case at {back}. The exhibition will open on time.", "Return the owl to the exhibition",
   ["Break the task into parts: how many minutes the owl has already spent under the lamp, how many more it needs, the walk to the library, the walk to the case.", "Minutes spent walking between lamps do not count: the owl is not under a lamp then.", "After the library, the owl still has to be carried to the case."], 3)
 ]}
L['uk'] = {
 "title": "Таємниця золотої сови",
 "intro": "З вітрини в коридорі другого поверху зникла картонна золота сова. На підставці калюжка, поруч розмокла записка, у якій читаються лише уривки: «...сушу... поверну до ...». О 14:30 учителька сфотографувала вітрину із совою, о 15:12 вітрина вже порожня. Після обіду в цьому крилі були четверо: Міра прикрашала подвір’я, Лев знімав школу для стінгазети, Саша готував театр до репетиції, Кім чергував у бібліотеці. Ніхто не зізнається. Виставка відкривається о 16:00. Треба зрозуміти, хто забрав сову, навіщо, і чи встигне вона повернутися.",
 "ending": "Сову ніхто не крав. Саша зачепив вазу, злякався, що картон розмокне, відніс сову сушитися в театр і залишив записку, яка одразу розмокла. Запис камери дав вікно у {wlen|хвилину|хвилини|хвилин}. Турнікет, журнал бібліотеки і знімки Лева виключили трьох. Журнал паперу і краплі води пов’язали Сашу з театром. Сова повернулася на вітрину о {back}, за {spare|хвилину|хвилини|хвилин} до відкриття. Учителька попросила Сашу наступного разу одразу казати дорослим.",
 "question": "У Саші не було алібі, а краплі води вели в театр. Чому другий доказ сильніший за перший?",
 "steps": [
  step("Коли забрали сову?", "Чергова знайшла запис камери в коридорі, але камера писала з перебоями: частина часу пропала. На всіх збережених кадрах видно вітрину. Чергова звірила годинник камери з точним і записала поправку.",
   ["З 14:30 до {c1} за годинником камери запис зберігся: сова на місці весь цей час.", "З {c1} до {c2} за годинником камери запису немає.", "З {c2} до 15:12 за годинником камери запис зберігся: вітрина порожня весь цей час.", "Годинник камери відстає від точного часу на {lag|хвилину|хвилини|хвилин}."],
   "У якому проміжку точного часу могли забрати сову?", "choice", ["З {c1} до {c2}", "З {nc1} до {nc2}", "З {w1} до {w2}", "З 14:30 до 15:12"],
   ["Це проміжок за годинником камери. Він відстає, отже справжній час інший.", "Годинник, що відстає, показує менше, ніж насправді. Поправку треба додати, а не відняти.", "", "Між знімками вчительки 42 хвилини, але запис камери дозволяє звузити проміжок."],
   "Останній кадр із совою: {c1} за камерою, а за точним часом на {lag|хвилину|хвилини|хвилин} більше, {w1}. Перший кадр без сови: {c2} за камерою, тобто {w2}. Сову забрали між {w1} і {w2}.",
   "Вікно лише {wlen|хвилина|хвилини|хвилин}: з {w1} до {w2} за точним часом. Тепер перевіримо, хто з чотирьох міг у цей час опинитися біля вітрини.", "Перевірити, де були всі четверо",
   ["Знайди на записі два моменти: останній кадр, де сова ще є, і перший кадр, де її вже немає.", "Годинник, що відстає, показує менше, ніж точний. Виріши, додавати поправку чи віднімати.", "Поправ обидва кінці проміжку на те саме число хвилин."], 0),
  step("У кого є алібі?", "Чергова зібрала все, що відомо про чотирьох. Вітрина стоїть у коридорі другого поверху. Сову забрали між {w1} і {w2}. Перевір кожного: чи міг він опинитися біля вітрини хоча б на хвилину в цьому проміжку. Усі часи нижче точні, якщо не сказано інше.",
   ["Вхід до школи один, через турнікет, він записує кожен прохід. Міра вийшла о 14:35 і повернулася о 15:20.", "Кім чергував у бібліотеці в іншому крилі. Від бібліотеки до вітрини йти 4 хвилини. За журналом Кім видавав книжки о {k1}, {k2}, {k3} і {k4}.", "Лев увесь час носив фотоапарат, годинник якого поспішає на {lf|хвилину|хвилини|хвилин}. Знімки за годинником фотоапарата: спортзал о {gcam}, їдальня о {cacam} і о {cbcam}.", "Від спортзалу до вітрини йти 6 хвилин, від їдальні до вітрини 5 хвилин.", "Саша готував театр. Репетиція закінчилася о 14:50, театр за 2 хвилини від вітрини. Після 14:50 Сашу ніхто не бачив до 15:15."],
   "Познач усіх, хто не міг бути біля вітрини між {w1} і {w2}.", "multi", ["Міра", "Лев", "Саша", "Кім"], [],
   "Міра була за турнікетом з 14:35 до 15:20. Кім відмічений у бібліотеці о {k2} і {k3}: між ними 6 хвилин, а дорога до вітрини і назад займає 8. Знімки Лева за точним часом: спортзал {g}, їдальня {ca} і {cb}. Між знімками по 5 хвилин, а від спортзалу до вітрини 6 хвилин, від їдальні 5, і ще треба встигнути назад. Ні в кого з трьох немає вільного проміжку. Лише Саша після 14:50 ніким не відмічений, а театр за дві хвилини від вітрини.",
   "Міра, Кім і Лев не могли бути біля вітрини. Залишається Саша. Але відсутність алібі ще не доказ: потрібні докази, які пов’язують саме його із совою.", "Шукати докази",
   ["Перевіряй кожного окремо: де він точно був у проміжку і скільки хвилин йому йти до вітрини.", "У Лева годинник фотоапарата поспішає. Спершу переведи всі його знімки в точний час.", "У Кіма і Лева є відмітки часу. Порахуй хвилини між сусідніми відмітками і порівняй з дорогою до вітрини і назад."], 1),
  step("Який доказ справжній?", "Бібліотекарка показує журнал видачі паперу, а чергова пройшла коридором з ліхтариком. Один запис у журналі виглядає підозріло, але не поспішай: спершу виріши, що зі знайденого справді пов’язане із совою.",
   ["Журнал: {sp} Саша взяв 3 аркуші цупкого паперу. {lp} Лев узяв 1 аркуш кольорового паперу для стінгазети.", "На підлозі краплі води. Вони ведуть від вітрини до сходів і обриваються біля дверей театру.", "На підставці сови слід від перекинутої вази, сама ваза стоїть поруч порожня.", "У записці читаються уривки: «...сушу... поверну до ...». Почерк розмитий."],
   "Який висновок правильний?", "choice", ["Папір брали і Саша, і Лев, тому підозрюваних знову двоє", "Саша взяв цупкий папір о {sp}, усередині вікна, а краплі ведуть у театр, де він працював. Обидва докази вказують на нього", "Лев узяв папір пізніше, о {lp}, отже це він забрав сову", "Записка розмита і нічого не доводить, тому доказів поки немає"],
   ["Лев не міг бути біля вітрини, це вже доведено знімками. Запис про нього в журналі нічого не змінює.", "", "У Лева є алібі на все вікно. Один рядок у журналі його не скасовує.", "Записка сама по собі слабкий доказ. Але є ще журнал і краплі: склади їх разом."],
   "Запис про Лева справжній, але Лев виключений знімками, тому це хибний слід. Запис про Сашу потрапляє у вікно {w1}-{w2}, а цупкий папір потрібен, щоб сушити мокрий виріб. Краплі ведуть саме в театр, де Саша працював. Записка підтверджує: сову не вкрали, а віднесли сушити.",
   "Версія: Саша зачепив вазу, вода залила підставку, він узяв у бібліотеці цупкий папір і відніс сову сушитися в театр, а записку залишив біля вітрини. Перевіримо версію в театрі і вирішимо, чи встигне сова повернутися до 16:00.", "Іти в театр",
   ["Спершу згадай, кого вже виключено. Доказ проти виключеної людини нічого не змінює.", "Перевір час кожного запису журналу: чи потрапляє він у вікно {w1}-{w2}?", "Куди ведуть краплі і хто там працював у цей час?"], 2),
  step("Чи встигне сова на виставку?", "У театрі Саша сушить сову на цупкому папері під лампою. Він підтверджує: зачепив вазу, злякався, що картон розмокне, і відніс сову сушитися, а записку залишив біля вітрини. Тепер головне: виконати інструкцію, не зірвати репетицію і повернути сову до відкриття.",
   ["Саша поклав сову під лампу о {t0}.", "Інструкція до набору: після намокання тримати під лампою не менше ніж {need|хвилину|хвилини|хвилин}, потім перевірити, що картон сухий. Переносити можна й раніше, але час під лампою все одно має набратися.", "Репетиція в театрі починається о 15:30. Саша забере сову зі сцени о 15:28.", "У бібліотеці є така сама лампа. Від театру до бібліотеки йти 6 хвилин, від бібліотеки до вітрини 4 хвилини.", "Виставка відкривається о 16:00."],
   "О котрій найраніше сова повернеться на вітрину, якщо виконати інструкцію? Введи час ГГ:ХХ.", "time", [], [],
   "У театрі під лампою з {t0} до 15:28: {sofar|хвилина|хвилини|хвилин}. До {need} бракує {rem}. Дорога до бібліотеки 6 хвилин, під лампу сова потрапляє о 15:34, ще {rem|хвилина|хвилини|хвилин} дають {done}. Перевірка сухості і 4 хвилини до вітрини: сова на місці о {back}, за {spare|хвилину|хвилини|хвилин} до відкриття.",
   "План готовий: о 15:28 зі сцени, о 15:34 під лампу в бібліотеці, о {done} перевірка, о {back} сова на вітрині. Виставка відкриється вчасно.", "Повернути сову на виставку",
   ["Розбий задачу на частини: скільки хвилин сова вже під лампою, скільки ще потрібно, дорога до бібліотеки, дорога до вітрини.", "Хвилини в дорозі між лампами не рахуються: сова в цей час не під лампою.", "Після бібліотеки сову ще треба донести до вітрини."], 3)
 ]}
if __name__ == '__main__':
    write_case('owl', '001', L, variants())
